# Generated by Django 2.0.13 on 2023-02-28 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('age', models.IntegerField()),
                ('status', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='DompetDigital',
            fields=[
                ('userprofile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='userprofiles.UserProfile')),
                ('saldo', models.IntegerField()),
            ],
        ),
    ]
