# Generated by Django 2.0.13 on 2023-03-03 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DompetDigital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('O', 'Ovo'), ('D', 'Dana'), ('G', 'Gopay')], db_index=True, max_length=1)),
                ('saldo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=255, unique=True)),
                ('age', models.IntegerField()),
                ('status', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='dompetdigital',
            name='user_profiles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofiles.UserProfile'),
        ),
    ]
